# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FakestoreMobileReact' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FakestoreMobileReact

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'FakestoreMobileReactTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
